spring.datasource.url=jdbc:h2:file:./data
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.hibernate.ddl-auto=update
# H2 Console'u aktif et
spring.h2.console.enabled=true
# Console'un hangi adreste çal??aca??n? belirt
spring.h2.console.path=/h2-console