name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    # Bu bölüm, bu işteki tüm 'run' komutlarının
    # varsayılan olarak './backend' klasöründe çalışmasını sağlar.
    defaults:
      run:
        working-directory: ./backend

    steps:
    - uses: actions/checkout@v4
    
    - name: List files in the repository
    run: ls -R

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      # Artık klasör belirtmemize gerek yok, çünkü işe zaten doğru klasörde başlıyor.
      run: mvn -B package --file pom.xml
